asd

diff --git a/external/Shimmer-Java-Android-API/.github/workflows/gradle.yml b/external/Shimmer-Java-Android-API/.github/workflows/gradle.yml
--- a/external/Shimmer-Java-Android-API/.github/workflows/gradle.yml
+++ b/external/Shimmer-Java-Android-API/.github/workflows/gradle.yml
@@ -8,51 +8,51 @@
 name: Java CI with Gradle
 
 on:
-  push:
-    branches: [ "master" ]
-  pull_request:
-    branches: [ "master" ]
+    push:
+        branches: ["master"]
+    pull_request:
+        branches: ["master"]
 
 jobs:
-  build:
+    build:
 
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
+        runs-on: ubuntu-latest
+        permissions:
+            contents: read
 
-    steps:
-      - uses: actions/checkout@v4
-      - name: Set up JDK 11
-        uses: actions/setup-java@v4
-        with:
-          java-version: '11'
-          distribution: 'temurin'
+        steps:
+            -   uses: actions/checkout@v4
+            -   name: Set up JDK 11
+                uses: actions/setup-java@v4
+                with:
+                    java-version: '11'
+                    distribution: 'temurin'
 
-        # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
-        # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
-        # - name: Setup Gradle
-        #   uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0
+                # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
+                # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
+                # - name: Setup Gradle
+                #   uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0
 
-        # - name: Make gradlew executable
-        #   run: chmod +x ./ShimmerDriver/gradlew
-      
-      # - name: Build with Gradle Wrapper
-      #   run: ./ShimmerDriver/gradlew build
+                # - name: Make gradlew executable
+                #   run: chmod +x ./ShimmerDriver/gradlew
 
-      # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
-      # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
-      #
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0
-        with:
-          gradle-version: '8.10.2'
-      - name: Build with Gradle 8.10.2
-        run: |
-          cd ShimmerDriverPC       
-          gradle build -i
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: '**/build/test-results/test/*.xml'
+            # - name: Build with Gradle Wrapper
+            #   run: ./ShimmerDriver/gradlew build
+
+            # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
+            # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
+            #
+            -   name: Setup Gradle
+                uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0
+                with:
+                    gradle-version: '8.10.2'
+            -   name: Build with Gradle 8.10.2
+                run: |
+                    cd ShimmerDriverPC       
+                    gradle build -i
+            -   name: Publish Test Report
+                uses: mikepenz/action-junit-report@v4
+                if: success() || failure() # always run even if the previous step fails
+                with:
+                    report_paths: '**/build/test-results/test/*.xml'
 
